[package]
name = "verity-hash"
version = "0.1.0"
edition = "2021"
description = "dm-verity hash image verifier"
license = "MIT"
repository = "https://github.com/losfair/verity-hash"
authors = ["Heyang Zhou"]

[dependencies]
faster-hex = "0.10"
sha2 = "0.10"
